### ISSUE TITLE
Gateway status icon on Gateways page

### ISSUE THREAD

**Issue by shepiloff** [brocaar/chirpstack-application-server#386]
### Is this a bug or a feature request?
feature request
### What did you expect?
gateway status display with red/green icon near each GW on GW list page,  not only marker color on the GW map page.

**Comment by brocaar** [comment]
Maybe an icon might make the table a bit "busy", but a "Last seen" column would be helpful (and possible after the stats refactor that I have done a few versions ago). Then when the last seen timestamp is  e.g. > 5 minutes ago, mark it red.

**Comment by mmrein** [comment]
Ok, I added a "Last seen" column to gateway list in same fashion as it is on devices list. I would also  change the "Last seen" info on gateway details page to "Last seen at" value - in the same fashion as in the device details page.

I'm hesitating on the color marking tho mainly because you can quite easily see if the GW has been seen "few seconds ago" or "2 moths ago".
