### ISSUE TITLE
read configuration file error

### ISSUE THREAD

**Issue by geogerli** [brocaar/chirpstack-application-server#446]
### Is this a bug or a feature request?
bug
### What did you expect?
no configuration file found
### What happened?
process exits
### What version are your using?
3.9.0
### How can your issue be reproduced?
a read configuration file error occurs ,when the 'chirpstack-application-server.toml' file does not exist.the dependent viper v1.4.0 is ok

**Comment by shepiloff** [comment]
exactly. without chirpstack-application-server.toml  app server will not start.  what did you expect?

**Comment by geogerli** [comment]
![f427d1e64b89589ed05a23d9fe9d619](https://user-images.githubusercontent.com/8215019/77600289-63bbd400-6f42-11ea-9903-0811d78d6885.png)

**Comment by geogerli** [comment]
If you change the version of viper in the go.mod file to v1.4.0, it will run normally after compiling

**Comment by brocaar** [comment]
@geogerli  your issue was a bit difficult for me to understand as I was not sure how to reproduce it. 

However it is clear now with the screenshot. The issue is that viper (at least < 1.4) detects the binary as config file (when you execute `./chirpstack-application-server configfile`) which for obvious reasons fails. However when you execute `./build/chirpstack-application-server configfile` it does work.

Would you like to create a PR to update the viper dependency?

**Comment by geogerli** [comment]
What does PR mean? This bug may be viper's own, and the following steps are required to reproduce it.

![op](https://user-images.githubusercontent.com/8215019/77731079-2ee07780-703d-11ea-9d5a-856950e04838.png)

**Comment by brocaar** [comment]
> What does PR mean? 

Pull Request :-)
