### ISSUE TITLE
I use the new password to log in to the page and respond slowly

### ISSUE THREAD

**Issue by guo652917087** [brocaar/chirpstack-application-server#467]
I have a problem with the latest branch, running on the Raspberry Pi, adding users, or changing the password, or logging in with something other than "admin / admin", the browser page only shows execution completion after more than 30 seconds, using api Similarly, using the new account to execute the login API, you need to wait for more than 30 seconds to return the jwt value. I use "admin / admin" login browser response time is normal.

**Comment by brocaar** [comment]
Please see the following setting:

```
# The number of times passwords must be hashed. A higher number is safer as
# an attack takes more time to perform.
password_hash_iterations=100000
```

The default `admin` user is hashed with `1` iteration, since the password (`admin`) is already known. When you reset the password, the above setting is used. The higher the value, the more CPU time is consumed.

Setting this to a lower value + resetting the password should do the trick.
